### ISSUE TITLE
No audio input/output on archlinux 6.8.5 (matebook 14 2020 KLVL-WXX9 (M1010))

### ISSUE THREAD

**Issue by antoineok** [codepayne/linux-sound-huawei#35]
Hello, i have some audio problems on my archlinux (kernel: 6.8.5-arch1-1).
I have a matebook 14 2020 KLVL-WXX9 (M1010)

The only way to have audio in is wireless earbuds and the only way to have audio out is wireless earbuds or HDMI.
Here are the outputs of the following commands:
inxi -Axxx:
```
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio vendor: Huaqin
    driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
    bus-ID: 04:00.1 chip-ID: 1002:1637 class-ID: 0403
  Device-2: AMD ACP/ACP3X/ACP6x Audio Coprocessor vendor: Huaqin driver: N/A
    pcie: speed: 16 GT/s lanes: 16 bus-ID: 04:00.5 chip-ID: 1022:15e2
    class-ID: 0480
  API: ALSA v: k6.8.5-arch1-1 status: kernel-api
  Server-1: PipeWire v: 1.0.4 status: active with: 1: pipewire-pulse
    status: active 2: wireplumber status: active 3: pipewire-alsa type: plugin
    4: pw-jack type: plugin
```
    
aplay -l:
```
**** Liste des périphériques matériels PLAYBACK ****
carte 0 : Generic [HD-Audio Generic], périphérique 3 : HDMI 0 [HDMI 0]
  Sous-périphériques : 1/1
  Sous-périphérique #0 : subdevice #0
carte 0 : Generic [HD-Audio Generic], périphérique 7 : HDMI 1 [HDMI 1]
  Sous-périphériques : 1/1
  Sous-périphérique #0 : subdevice #0
```
  
cat /proc/asound/cards:
```
 0 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xd03c0000 irq 76
```
